/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface PrimeUiTest {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPrimeUiTestElement extends Components.PrimeUiTest, HTMLStencilElement {
    }
    var HTMLPrimeUiTestElement: {
        prototype: HTMLPrimeUiTestElement;
        new (): HTMLPrimeUiTestElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "prime-ui-test": HTMLPrimeUiTestElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface PrimeUiTest {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "prime-ui-test": PrimeUiTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "prime-ui-test": LocalJSX.PrimeUiTest & JSXBase.HTMLAttributes<HTMLPrimeUiTestElement>;
        }
    }
}
